import { Resend } from "resend";
import { createClient } from "@supabase/supabase-js";

// Initialize Resend
const resend = new Resend(process.env.RESEND_API_KEY);

// Initialize Supabase with Service Role to bypass RLS for internal logging
const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
);

export const sendBlueprintEmail = async (email: string, name: string) => {
  const isProd = process.env.NODE_ENV === "production";
  const myEmail = process.env.MY_EMAIL || "omolloandrew37@gmail.com";

  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000";

  const fromAddress = isProd
    ? "Andrew | SleekSites <andrew@contact.sleeksites.co.ke>"
    : "SleekSites Testing <onboarding@resend.dev>";

  const recipient = isProd ? email : process.env.TEST_RECEIPENT_EMAIL || email;

  try {
    // 1. DATABASE LOGGING & TOKEN GENERATION
    // We upsert the lead and select the download_token (generated by Supabase)
    const { data: leadData, error: dbError } = await supabase
      .from("leads")
      .upsert({ name, email }, { onConflict: "email" })
      .select("download_token")
      .single();

    if (dbError) throw new Error(`Supabase Sync Error: ${dbError.message}`);

    const token = leadData.download_token;

    // 2. CONSTRUCT SECURE URL (Using the token instead of email)
    const secureDownloadUrl = `${baseUrl}/api/download?token=${token}`;

    // 3. RESEND AUDIENCE SYNC
    try {
      if (process.env.RESEND_AUDIENCE_ID) {
        await resend.contacts.create({
          email: email,
          firstName: name,
          unsubscribed: false,
          audienceId: process.env.RESEND_AUDIENCE_ID,
        });
      }
    } catch (e) {
      console.log("Resend Audience sync skipped or lead already exists.");
    }

    // 4. THE LEAD EMAIL (Transmittal Style)
    const leadEmailPromise = resend.emails.send({
      from: fromAddress,
      to: [recipient],
      replyTo: myEmail,
      subject:
        "TRANSMITTAL: The 2026 Construction Digital Credibility Blueprint",
      html: `
        <div style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #0f172a; max-width: 600px; margin: 0 auto; line-height: 1.5; border: 1px solid #e2e8f0; border-radius: 12px; overflow: hidden;">
          <div style="background-color: #0f172a; padding: 30px; color: #ffffff;">
            <h2 style="margin: 0; letter-spacing: -1px; font-weight: 900; text-transform: uppercase; font-size: 20px;">SleekSites<span style="color: #3b82f6;">.</span></h2>
            <p style="margin: 5px 0 0 0; font-size: 10px; font-weight: bold; text-transform: uppercase; letter-spacing: 0.2em; color: #94a3b8;">Ref: Engineering Digital Systems / 2026-BCB</p>
          </div>

          <div style="padding: 40px 30px;">
            <h1 style="font-size: 28px; font-weight: 800; letter-spacing: -0.03em; margin-bottom: 20px; color: #1e293b;">Secure Document Transmittal</h1>
            <p style="margin-bottom: 24px; font-size: 16px;">Hello ${name},</p>
            <p style="margin-bottom: 24px; font-size: 16px;">
              Your request for the <strong>Construction Digital Credibility Blueprint</strong> has been processed. This architecture is designed to transition your firm into a <strong>Tier 1 digital authority.</strong>
            </p>

            <div style="background-color: #f1f5f9; border-radius: 12px; padding: 24px; margin: 32px 0; border: 1px solid #e2e8f0;">
              <p style="margin: 0 0 8px 0; font-size: 12px; color: #64748b; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em;">Authorized Access Only:</p>
              <p style="margin: 0 0 20px 0; font-weight: 800; font-size: 18px; color: #0f172a;">2026_Digital_Credibility_Blueprint.pdf</p>
              <a href="${secureDownloadUrl}" style="display: inline-block; background-color: #2563eb; color: #ffffff; padding: 16px 32px; text-decoration: none; border-radius: 8px; font-weight: 800;">
                Access the Blueprint →
              </a>
            </div>

            <p style="margin-bottom: 24px; font-size: 15px; color: #334155;">
              <strong>Key Directive:</strong> Pay close attention to <em>Section 3: The Gmail Trap</em>. Professional domain infrastructure is now a procurement requirement for major tenders.
            </p>

            <div style="margin-top: 40px; padding-top: 30px; border-top: 2px dashed #e2e8f0;">
              <p style="font-size: 14px; color: #64748b; margin: 0;">Respectfully,<br /><br />
                <strong style="color: #0f172a; font-size: 16px;">Andrew</strong><br />Managing Partner, SleekSites
              </p>
            </div>
          </div>
          
          <div style="background-color: #f8fafc; padding: 20px 30px; text-align: center;">
            <p style="font-size: 11px; color: #94a3b8; margin: 0;">
              © 2026 SleekSites Engineering Digital Systems. This transmittal is confidential.
            </p>
          </div>
        </div>
      `,
    });

    // 5. THE GMAIL NOTIFICATION
    const internalAlertPromise = resend.emails.send({
      from: isProd
        ? "SleekSites HQ <system@contact.sleeksites.co.ke>"
        : fromAddress,
      to: [myEmail],
      subject: `⚡ [NEW LEAD] ${name}`,
      html: `
        <div style="font-family: sans-serif; padding: 24px; background: #fff; border: 2px solid #2563eb; border-radius: 8px;">
          <h2 style="color: #2563eb; margin-top: 0;">New Construction Lead</h2>
          <p><strong>Name:</strong> ${name}</p>
          <p><strong>Email:</strong> ${email}</p>
          <p style="font-size: 12px; color: #666;">Logged in Supabase with Token: <code>${token}</code></p>
        </div>
      `,
    });

    const [leadResult] = await Promise.all([
      leadEmailPromise,
      internalAlertPromise,
    ]);
    if (leadResult.error) throw new Error(leadResult.error.message);

    return { success: true, data: leadResult.data };
  } catch (err: any) {
    console.error("Critical Error:", err);
    return {
      success: false,
      error: err.message || "Delivery pipeline failure.",
    };
  }
};
